// Copyright 2024-2025 Irreducible Inc.
// Copyright 2026 The Binius Developers

use std::iter;

use binius_field::{ExtensionField, Field, FieldOps, PackedField, WideMul};

#[inline]
pub fn inner_product<F: Field>(
	a: impl IntoIterator<Item = F>,
	b: impl IntoIterator<Item = F>,
) -> F {
	inner_product_subfield(a, b)
}

#[inline]
pub fn inner_product_scalars<F: FieldOps>(
	a: impl IntoIterator<Item = F>,
	b: impl IntoIterator<Item = F>,
) -> F {
	itertools::zip_eq(a, b).map(|(a_i, b_i)| b_i * a_i).sum()
}

#[inline]
pub fn inner_product_subfield<F, FSub>(
	a: impl IntoIterator<Item = FSub>,
	b: impl IntoIterator<Item = F>,
) -> F
where
	F: Field + ExtensionField<FSub>,
	FSub: Field,
{
	itertools::zip_eq(a, b).map(|(a_i, b_i)| b_i * a_i).sum()
}

/// Compute the inner product of two scalar sequences generated by iterators of packed elements.
///
/// ## Preconditions
///
/// * `a` and `b` have length `1 << log_n.saturating_sub(P::LOG_WIDTH)`
#[inline]
pub fn inner_product_packed<F, P>(
	log_n: usize,
	a: impl ExactSizeIterator<Item = P>,
	b: impl ExactSizeIterator<Item = P>,
) -> F
where
	F: Field,
	P: PackedField<Scalar = F>,
{
	assert_eq!(a.len(), 1 << log_n.saturating_sub(P::LOG_WIDTH)); // pre-condition
	assert_eq!(b.len(), 1 << log_n.saturating_sub(P::LOG_WIDTH)); // pre-condition

	// Accumulate the products in unreduced (wide) form and reduce a single time at the end.
	// For packed `GF(2^128)` fields this amortizes the reduction cost across all products.
	// For every other field the widening multiply is the trivial one, so this is a plain
	// product-then-sum.
	let wide_sum = iter::zip(a, b)
		.map(|(a_i, b_i)| P::wide_mul(a_i, b_i))
		.sum::<<P as WideMul>::Output>();
	P::reduce(wide_sum).into_iter().take(1 << log_n).sum()
}

#[cfg(test)]
mod tests {
	use binius_field::{Ghash128b, PackedBinaryGhash4x128b, PackedField, Random};
	use rand::{SeedableRng, rngs::StdRng};

	use super::*;

	type P = PackedBinaryGhash4x128b;
	type F = Ghash128b;

	// The packed inner product defers the `GF(2^128)` reduction (widening multiply).
	// Check the reduced result against a naive scalar-by-scalar reference.
	#[test]
	fn test_inner_product_packed_matches_naive() {
		let mut rng = StdRng::seed_from_u64(42);

		for log_n in [4, 8, 12] {
			let n = 1 << log_n;
			let a = (0..n / P::WIDTH)
				.map(|_| P::random(&mut rng))
				.collect::<Vec<P>>();
			let b = (0..n / P::WIDTH)
				.map(|_| P::random(&mut rng))
				.collect::<Vec<P>>();

			let naive = iter::zip(&a, &b)
				.flat_map(|(a_i, b_i)| iter::zip(a_i.iter(), b_i.iter()))
				.map(|(a_j, b_j)| a_j * b_j)
				.sum::<F>();

			let packed: F = inner_product_packed(log_n, a.iter().copied(), b.iter().copied());
			assert_eq!(packed, naive, "mismatch at log_n={log_n}");
		}
	}

	// Below the packing width the trailing scalars of the one word must not contribute.
	#[test]
	fn test_inner_product_packed_below_the_packing_width() {
		let mut rng = StdRng::seed_from_u64(0);

		let a = P::random(&mut rng);
		let b = P::random(&mut rng);

		let packed: F = inner_product_packed(0, iter::once(a), iter::once(b));
		assert_eq!(packed, a.iter().next().unwrap() * b.iter().next().unwrap());
	}
}
